
LOCAL_CFLAGS += \
-DHAVE_ALLOCA_H \
-DHAVE_LIMITS_H \
-DHAVE_DECL_BASENAME \
-DHAVE_DECL_FFS \
-DHAVE_DECL_FREE \
-DHAVE_DECL_FSEEKO \
-DHAVE_DECL_FTELLO \
-DHAVE_DECL_GETENV \
-DHAVE_DECL_MALLOC \
-DHAVE_DECL_REALLOC \
-DHAVE_DECL_SNPRINTF \
-DHAVE_DECL_STPCPY \
-DHAVE_DECL_STRSTR \
-DHAVE_DECL_GETOPT \
-DHAVE_DECL_VSNPRINTF \
-DHAVE_DIRENT_H \
-DHAVE_DLFCN_H \
-DHAVE_FCNTL \
-DHAVE_FCNTL_H \
-DHAVE_FDOPEN \
-DHAVE_FILENO \
-DHAVE_FSEEKO \
-DHAVE_FTELLO \
-DHAVE_GETGID \
-DHAVE_GETUID \
-DHAVE_INTTYPES_H \
-DHAVE_INTPTR_T \
-DHAVE_UINTPTR_T \
-DHAVE_MADVISE \
-DHAVE_MEMORY_H \
-DHAVE_MMAP \
-DHAVE_MPROTECT \
-DHAVE_SETITIMER \
-DHAVE_STDDEF_H \
-DHAVE_STDINT_H \
-DHAVE_STDLIB_H \
-DHAVE_STRINGS_H \
-DHAVE_STRING_H \
-DHAVE_STRTOULL \
-DHAVE_SYSCONF \
-DHAVE_PSIGNAL \
-DHAVE_SYS_FILE_H \
-DHAVE_SYS_WAIT_H \
-DHAVE_SYS_STAT_H \
-DHAVE_SYS_TIME_H \
-DHAVE_SYS_TYPES_H \
-DHAVE_TIME_H \
-DHAVE_UNISTD_H \
-DHAVE_ZLIB_H \
-DPACKAGE_BUGREPORT=\"\" \
-DPACKAGE_URL=\"\" \
-DSTDC_HEADERS \
-DSTRING_WITH_STRINGS \
-DTIME_WITH_SYS_TIME \
-DUSE_MMAP \
-D_ALL_SOURCE \
-D_POSIX_PTHREAD_SEMANTICS \
-D_TANDEM_SOURCE \
-D__EXTENSIONS__ \
-DPACKAGE_TARNAME=\"$(LOCAL_MODULE)\" \
-DSIZEOF_INT=4 \
-DUNSIGNED_64BIT_TYPE=uint64_t \

ifneq ($(LOCAL_VERSION),)
LOCAL_CFLAGS += -DVERSION=\"$(LOCAL_VERSION)\" \
-DPACKAGE_VERSION=\"$(LOCAL_VERSION)\" \
-DPACKAGE_STRING=\"$(LOCAL_MODULE)-$(LOCAL_VERSION)\"

#LOCAL_VERSION :=

endif


LOCAL_CFLAGS += \
-DTARGET_ALIAS=\"arm-unknown-linux-gnu\" \
-DTARGET_CANONICAL=\"arm-unknown-linux-gnu\" \
-DTARGET_OS=\"linux-gnu\" \
-DTARGET_CPU=\"arm\" \
-DTARGET_VENDOR=\"unknown\"



